# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=250)),
                ('site', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_title', models.CharField(max_length=1000)),
                ('url_name', models.CharField(max_length=250)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.Type')),
            ],
        ),
    ]
